// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxvc8jw7wbLqoAtTI2L5W2d3W8YejkaIU',
    appId: '1:44034657523:android:776d7d7baf726f1581bb86',
    messagingSenderId: '44034657523',
    projectId: 'flutter-final-f2191',
    storageBucket: 'flutter-final-f2191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4iZg233iHmMpLntKJ6IF4__XTlOT0dcM',
    appId: '1:44034657523:ios:2073f46f5a0485e781bb86',
    messagingSenderId: '44034657523',
    projectId: 'flutter-final-f2191',
    storageBucket: 'flutter-final-f2191.firebasestorage.app',
    iosBundleId: 'com.example.crossFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4iZg233iHmMpLntKJ6IF4__XTlOT0dcM',
    appId: '1:44034657523:ios:2073f46f5a0485e781bb86',
    messagingSenderId: '44034657523',
    projectId: 'flutter-final-f2191',
    storageBucket: 'flutter-final-f2191.firebasestorage.app',
    iosBundleId: 'com.example.crossFinal',
  );
}
